name: Daily Heartbeat

on:
  schedule:
    # 12:00 IST daily -> 06:30 UTC (IST - 5:30). Run a couple minutes after.
    - cron: "35 6 * * *"

jobs:
  hb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Send heartbeat
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          HEARTBEAT: "1"
        run: python monitor.py
