name: Nifty Hourly Scanner

on:
  workflow_dispatch: {}
  schedule:
    # Run shortly after each hourly close (IST) during market days (Mon-Fri)
    # Hourly closes in IST around 10:15, 11:15, 12:15, 13:15, 14:15, 15:15
    # Convert to UTC (IST - 5:30): 04:45..09:45 -> we trigger at :50 for safety.
    - cron: "50 4 * * 1-5"
    - cron: "50 5 * * 1-5"
    - cron: "50 6 * * 1-5"
    - cron: "50 7 * * 1-5"
    - cron: "50 8 * * 1-5"
    - cron: "50 9 * * 1-5"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Scan NIFTY
        env:
          # Optional overrides
          NIFTY_TICKER: "^NSEI"
          EMA_PERIOD: "20"
          ST_ATR_PERIOD: "7"
          ST_MULTIPLIER: "3.5"
          OTM_GAP_POINTS: "100"
          LOG_LEVEL: "INFO"
          # Telegram secrets (set these in repo → Settings → Secrets → Actions)
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor.py
